### PR TITLE
External modules2

### PR DESCRIPTION
**Pull request by kofifus**
This is one of a set of 3 PRs to cornerstone, cornerstoneTools and cornerstoneWADOImageLoader

- external is now a default export
- fixed some missing .js extensions

### CODE REVIEW

**Comment by swederik** [comment]
Thanks!

Maybe we should try to add https://github.com/benmosher/eslint-plugin-import to stop us from forgetting the .js file extensions?

I just tested it on a branch here:

https://github.com/chafey/cornerstone/tree/eslint-plugin-import

and it looks like it could suit our needs. What do you think?

**Comment by kofifus** [comment]
Yeah I think that's a good idea, it's very tedious to keep fixing this. In general this is a webpack issue as it accepts a syntax that is not valid JS

**Comment by swederik** [comment]
I just fixed the missing .js extensions and added eslint-plugin-import to prevent these errors in the future. I won't bother switching external to default export at this point because we will be removing 'external' altogether in version 2.

**Comment by kofifus** [comment]
Hi Erik,

- Since you merged cornerstoneTools I think it makes sense to make external the default export on cornerstone as well, otherwise we are left with two different ways of using external.

- Below are instructions for loading ES6 modules directly using latest Chrome. I would prefer if you/someone else can create the wiki page. These instructions assume that this PR and https://github.com/chafey/cornerstoneWADOImageLoader/pull/144 are merged as well:

1. clone cornerstone modules. For example:
```
cd \myproject
md cornerstone
cd cornerstone
git clone https://github.com/chafey/cornerstone.git
git clone https://github.com/chafey/cornerstoneMath.git
git clone https://github.com/chafey/dicomParser.git
git clone https://github.com/chafey/cornerstoneTools.git
git clone https://github.com/chafey/cornerstoneWADOImageLoader.git
```

2. create ie \myproject\cornerstone\cornerstoneLoader.js like this:
```
import * as cornerstone from './cornerstone/src/index.js';
import * as cornerstoneMath from './cornerstoneMath/src/index.js';
import * as dicomParser from './dicomParser/src/index.js';
import * as cornerstoneTools from './cornerstoneTools/src/index.js';
import * as cornerstoneWADOImageLoader from './cornerstoneWADOImageLoader/src/imageLoader/index.js';

cornerstoneTools.external.cornerstone = cornerstone;
cornerstoneTools.external.cornerstoneMath = cornerstoneMath;
cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
cornerstoneWADOImageLoader.external.dicomParser = dicomParser;
```

3. in your development html ie \myproject\myhtml.html have:
`<script type="module" src="./cornerstone/cornerstoneLoader.js"></script>`

Note that any code that uses cornerstone must be in a js file loaded with script type="module" - that is you cannot use cornerstone inside <script> tags in html files.

**Pull request closed without merging**
