### PR TITLE
Multi-layer composition

### PR DESCRIPTION
**Pull request by swederik**
This PR is relevant to #50 and https://github.com/OHIF/Viewers/issues/1

I'm putting this here to get some feedback on the work so far on layered composition for Cornerstone. The goal is to enhance Cornerstone by adding the ability to display multiple layers on a single element, each with their own images and settings. A related goal is to be able to support DICOM Segmentation objects.

Enabled elements can have multiple layers, each of which are rendered into an offscreen canvas and then rendered on top of each other onto the enabledElement's canvas in drawCompositeImage.

General changes:
- Added 'layers' property to enabledElement, which is an array of enabledElements
- Added 'syncViewports' boolean to enabledElement to control whether or not all layers should have linked pan / zoom / rotate
- Added addLayer / removeLayer / getLayers functions to facilitate control of the layers array inside an enabledElement
- Added addGrayscaleLayer and addColorLayer to renderGreyscaleImage and renderColorImage. These simply render into a layer's offscreen canvas.

Open questions (feedback would be appreciated!):
- What is the most obvious way to enable two stacks to be layered on top of each other? Typically stacks have their own toolData related to enabled elements in cornerstoneTools. A ton of tools use this stackData so I don't think it's a great idea to change that.
- Should we change the toolStateManager and synchronizers to associate to layers instead of enabledElements?

### Basic display from a DICOM Segmentation Storage object

_Notes:_ In the Segmentation Storage SOP Class:
- A single instance stores many frames, covering different reference instance slices
- A single frame only ever stores one label, in multi-label cases there are more frames than original instance slices, so there is no one-to-one mapping
- To display multiple labels on the same image, the developer would have to add code to find the proper frames to display based on Referenced Segment Number and Referenced SOP Instance UID for each frame. This is not hard, but not necessary at this time.

### CODE REVIEW

**Comment by fedorov** [comment]
Great to see this development!

**Comment by jasonklotzer** [comment]
I think this is really great! I like how clean the interface is; it is very similar in feel to the image blending in VTK.

A few comments/questions:
* I do think it will be useful to include some default color maps.
* Will you allow for some sort of manual registration between image sets due to spatial mismatch, etc? 
* Along these lines, will there be an API or maybe some wrapper function that will allow associating two or more image sets (such as in PT/CT or PT/MR) where there is no mismatch/alignment concern?
* Is there a way to make it more clear via the API to say what layer the ROI/tools are using for calculations? Will it always be the top most?

**Comment by jpambrun** [comment]
Is there any use-case for other mixing method than alpha?

**Comment by phdggg** [comment]
Hi swederik,
 Just want to check whether you have a plan to commit this into the master. If so, when will this happen? It's really useful for my project.
Thanks,
Mengda

**Comment by swederik** [comment]
Hi Mengda,

We are still working on this branch. It will hopefully be finished soon.

**Comment by jpambrun** [comment]
This coveralls bot is a bit verbose..

**Comment by swederik** [comment]
I was rebasing / force pushing the same commit, so I guess that's my fault. Sorry!

**Pull request merged**
