### PR TITLE
Convert to ES6 modules

### PR DESCRIPTION
**Pull request by zachasme**
Related to #34. I've set up the project to use ES6 modules, and pack it up using Rollup.

I'm quite sure it exposes the same API as before, but it should probably be double checked.

### CODE REVIEW

**Comment by zachasme** [comment]
I've now also committed some changes that lay the groundwork for publishing on npm, which would make the library work much better with my current project. In that regard you might wish to contact Roland Poulter (get his email with `npm owner ls cornerstone`) who is the current owner of "cornerstone" on npm. That package appears orphaned and Roland even removed its git repository, so he might allow you to take over the package name.

**Comment by jpambrun** [comment]
This is already on the roadmap. @swederik, @jasonklotzer can we make it happen soon?

**Comment by jasonklotzer** [comment]
Yes, def on the roadmap and looks like there are a few things converging on ES6 features for cornerstone. This commit looks pretty good. I think someone just needs to get it and test things out. 

Also sent a separate email to Roland Poulter w/r/t the NPM space.

**Comment by zachasme** [comment]
Do note that other cornerstone repositories (e.g. image loaders) also need to be reworked if the entire project is to be usable from npm.

(In that regard you might want to have a look at [lerna](https://github.com/lerna/lerna) which is a tool for managing/publishing js projects with multiple packages).

**Comment by swederik** [comment]
Hi Zach,

Thanks for your hard work on this. I am going to try to rebase it on top of master and make sure nothing is broken. I wanted to get all the other open PRs into master before attempting this transition.

**Comment by swederik** [comment]
So I've been working on this in the https://github.com/chafey/cornerstone/tree/zachasme-es6 branch.

I think it might be easier to split this PR into two components: one for ES6 and another one afterwards for dropping jQuery. Switching from jQuery events to CustomEvents seems to mean that everyone will need to update every event handler in their code. I'd rather migrate all the libraries to ES6 first and then think about CustomEvents.

We intend to keep using $.Deferred (or something like it) in the WADO Image Loader, so dropping the jQuery dependency from Cornerstone doesn't get us much.

**Comment by swederik** [comment]
Conversion to ES6 modules was done for 0.10.9 (https://github.com/chafey/cornerstone/releases/tag/0.10.9). Please create new tickets if you find any issues!

**Pull request closed without merging**
