### PR TITLE
Trigger events when changing cornerstone image cache

### PR DESCRIPTION
**Pull request by adreyfus**

### CODE REVIEW

**Comment by adreyfus** [comment]
For any questions or suggestions, you can contact me here or by email.

**Comment by adreyfus** [comment]
The added code is in functions that are tested by `imageCache_test`, so I don't understand why the coverage decreases.

**Comment by swederik** [comment]
Out of curiosity, what is the purpose of these events? Do you have an external module monitoring the cache or something? I would just expect, for example, that modifying the cache size would be something that you would do on your own, so I don't see why you would also need to bind an event to it ("CornerstoneImageCacheMaximumSizeChanged").

**Comment by adreyfus** [comment]
Yes, this events permit to monitor the cache.

**Pull request merged**
