### PR TITLE
Feature/drawComposite image sync hflip

### PR DESCRIPTION
**Pull request by adreyfus**

### CODE REVIEW

**Comment by swederik** [comment]
Should we add vflip as well?

**Comment by adreyfus** [comment]
I hesitated, but since vflip does not exist in the DICOM standard, I don't know why it exists in cornerstone.

**Comment by swederik** [comment]
I think that as long as we have vflip as a viewport property, we should also have it here. Could you add that? Thanks!

**Comment by adreyfus** [comment]
Done ^^

**Comment by swederik** [comment]
Thanks!

**Pull request merged**
